In [1]:
import numpy as np

In [5]:
a = np.array([1,2,3,4])

In [2]:
a


NameError: name 'a' is not defined

In [3]:
a

NameError: name 'a' is not defined

In [4]:
a

NameError: name 'a' is not defined

In [6]:
a

array([1, 2, 3, 4])

In [7]:
a

array([1, 2, 3, 4])

In [8]:
a * 6

array([ 6, 12, 18, 24])

In [9]:
a +8 

array([ 9, 10, 11, 12])

In [10]:
a +a 

array([2, 4, 6, 8])

In [11]:
b = np.array({1,2,3,4,5})

In [12]:
b

array({1, 2, 3, 4, 5}, dtype=object)

In [13]:
a + b 

TypeError: unsupported operand type(s) for +: 'int' and 'set'

In [16]:
c = np.array([[1,2,3],[4,5,6]])

In [17]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
c.shape

(2, 3)

In [19]:
c * .5

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [20]:
d = np.array([1,1.5,3,4.7])

In [21]:
d 

array([1. , 1.5, 3. , 4.7])

In [22]:
c * np.array([1,2.5,5])

array([[ 1. ,  5. , 15. ],
       [ 4. , 12.5, 30. ]])

In [23]:
a

array([1, 2, 3, 4])

In [26]:
a = np.ones(100).reshape(10,10)
a[1:9, 1:9]=0

In [27]:
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [28]:
a = np.ones(100).reshape(10,10)
a[1:9, 1:9]=0

In [29]:
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [30]:
a = np.arange(100).reshape(10,10)

In [31]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [32]:
a.sum()

4950

In [33]:
a.sum(axis=0)

array([450, 460, 470, 480, 490, 500, 510, 520, 530, 540])

In [34]:
a.sum(axis=1)

array([ 45, 145, 245, 345, 445, 545, 645, 745, 845, 945])

In [35]:
a.sum(axis=1, keepdims=True)

array([[ 45],
       [145],
       [245],
       [345],
       [445],
       [545],
       [645],
       [745],
       [845],
       [945]])